spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/animedb
    username: animedb
    password: animedb

  data:
    jdbc:
      repositories:
        enabled: false

  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: true

  liquibase:
    change-log: classpath:/db/changelog/master.yaml
    enabled: true

